- name: Pull artifact from intermediate registry
  command: >-
    skopeo --insecure-policy copy
    --src-creds={{ intermediate_registry.username }}:{{ intermediate_registry.password }}
    --dest-creds={{ buildset_registry.username }}:{{ buildset_registry.password }}
    {{ item.url }}
    docker://{{ buildset_registry.host }}:{{ buildset_registry.port }}/{{ item.metadata.repository }}:{{ item.metadata.tag }}
  when: "item.metadata.type | default('') == 'container_image'"
  loop: "{{ zuul.artifacts | default([]) }}"
  # no_log: true  TODO(corvus): replace
