- name: Install bind9utils
  package:
    name: bind9utils
    state: present
  become: yes

- name: Find zone files
  find:
    paths: '{{ zone_files }}'
    patterns: 'zone.db'
    recurse: yes
    file_type: 'file'
  register: zone_db_files

- name: 'Run checkzone'
  command: '/usr/sbin/named-checkzone {{ item.path.split("/")[-2] }} {{ item.path }}'
  loop: "{{ zone_db_files['files'] }}"
