- name: Install bind9utils
  package:
    name: bind9utils
    state: present
  become: yes

- name: Build zone.db list
  include_tasks: find.yaml
  when: not zone_db_files

- name: 'Run checkzone'
  command: '/usr/sbin/named-checkzone {{ item[0] }} {{ item[1] }}'
  loop: "{{ zone_db_files }}"
