- name: Log in to dockerhub
  command: "docker login -u {{ docker_credentials.username }} -p {{ docker_credentials.password }}"
  no_log: true
- name: Upload to dockerhub
  command: "docker push {{ item.repository }}:change_{{ zuul.change }}"
  loop: "{{ docker_images }}"
