---
# TODO(mordred) This needs to switch back to not being venv - venv is OpenStack
# specific.
tox_envlist: venv
tox_executable: tox

zuul_work_dir: "{{ zuul.project.src_dir }}"

zuul_output_dir: "{{ ansible_user_dir }}/zuul-output"
zuul_use_fetch_output: "{{ zuul_site_use_fetch_output|default(false) }}"
