- name: Create OpenStack config dir
  file:
    dest: ~/.config/openstack
    state: directory
    recurse: true

- name: Deploy clouds.yaml
  template:
    src: clouds.yaml.j2
    dest: ~/.config/openstack/clouds.yaml
    mode: 0440
