# The apt module can not be used for this since it installs python-apt
# which can not work until this command fixes the cache.
- name: Update apt cache
  become: yes
  command: apt-get update
  # ANSIBLE0006: ignore, since we cannot use the apt module
  tags:
    - skip_ansible_lint

- name: Update yum/dnf cache
  become: yes
  command: "{{ item }}"
  args:
    warn: false
  with_items:
    - "{{ ansible_pkg_mgr }} clean all"
    - "{{ ansible_pkg_mgr }} makecache -v"
  # verbose is needed in order to make it possible to debug potential failures

- name: Update zypper cache
  become: yes
  command: "{{ item }}"
  with_items:
    - zypper clean
    - zypper refresh

- name: Update Gentoo cache
  become: yes
  command: emerge-webrsync
