- name: Download archive
  uri:
    url: "{{ artifact.url }}"
    dest: "{{ download_artifact_directory }}"
  loop: "{{ build.artifacts }}"
  loop_control:
    loop_var: artifact
  when: "artifact.name == download_artifact_name or ((download_artifact_name | type_debug) == 'list' and artifact.name in download_artifact_name)"
