- name: Query Zuul API for artifact information
  uri:
    url: "{{ download_artifact_api }}/builds?{{ download_artifact_query }}"
  register: build
- name: Parse build response
  set_fact:
    build: "{{ build.json[0] }}"
- name: Download archive by name
  uri:
    url: "{{ artifact.url }}"
    dest: "{{ download_artifact_directory }}"
  loop: "{{ build.artifacts }}"
  loop_control:
    loop_var: artifact
  when:
    - "download_artifact_name is defined"
    - "artifact.name == download_artifact_name or ((download_artifact_name | type_debug) == 'list' and artifact.name in download_artifact_name))"
- name: Download archive by type
  uri:
    url: "{{ artifact.url }}"
    dest: "{{ download_artifact_directory }}"
  loop: "{{ build.artifacts }}"
  loop_control:
    loop_var: artifact
  when:
    - "download_artifact_type is defined"
    - "'metadata' in artifact and 'type' in artifact.metadata and (artifact.metadata.type == download_artifact_type or ((download_artifact_type | type_debug) == 'list' and artifact.metadata.type in download_artifact_type))"
