- name: Query Zuul API for artifact information
  uri:
    url: "{{ download_artifact_api }}/builds?{{ download_artifact_query }}"
  register: build
- name: Extract artifact URL
  set_fact:
    archive_url: "{{ (build.json[0].artifacts | selectattr('name', 'equalto', download_artifact_name) | list)[0].url }}"
- name: Download archive
  uri:
    url: "{{ archive_url }}"
    dest: "{{ zuul.executor.work_root }}"
