- name: Query Zuul API for artifact information
  uri:
    url: "{{ download_artifact_api }}/builds?{{ download_artifact_query }}"
  register: build
- name: Parse build response
  set_fact:
    build: "{{ build.json[0] }}"
- name: Download archive
  uri:
    url: "{{ artifact.url }}"
    dest: "{{ download_artifact_directory }}"
  loop: "{{ build.artifacts }}"
  loop_control:
    loop_var: artifact
  when: "artifact.name == download_artifact_name or ((download_artifact_name | type_debug) == 'list' and artifact.name in download_artifact_name)"
