- project:
    templates:
      - build-tox-docs
    check:
      jobs:
        - openstack-infra-base-integration-centos-7
        - openstack-infra-base-integration-debian-stable
        - openstack-infra-base-integration-fedora-latest
        - openstack-infra-base-integration-ubuntu-bionic
        - openstack-infra-base-integration-ubuntu-trusty
        - openstack-infra-base-integration-ubuntu-xenial
        - openstack-infra-base-integration-opensuse423
        - openstack-infra-multinode-integration-centos-7
        - openstack-infra-multinode-integration-debian-stable
        - openstack-infra-multinode-integration-fedora-latest
        - openstack-infra-multinode-integration-ubuntu-bionic
        - openstack-infra-multinode-integration-ubuntu-trusty
        - openstack-infra-multinode-integration-ubuntu-xenial
        - openstack-infra-multinode-integration-opensuse423
        - zuul-jobs-tox-linters
        - zuul-jobs-test-install-nodejs
        - zuul-jobs-test-install-pdk-dependencies
        - zuul-jobs-test-upload-git-mirror
        - zuul-jobs-test-registry
        - tox-py27
        - tox-py35
    gate:
      jobs:
        - openstack-infra-base-integration-centos-7
        - openstack-infra-base-integration-debian-stable
        - openstack-infra-base-integration-fedora-latest
        - openstack-infra-base-integration-ubuntu-bionic
        - openstack-infra-base-integration-ubuntu-trusty
        - openstack-infra-base-integration-ubuntu-xenial
        - openstack-infra-base-integration-opensuse423
        - openstack-infra-multinode-integration-centos-7
        - openstack-infra-multinode-integration-debian-stable
        - openstack-infra-multinode-integration-fedora-latest
        - openstack-infra-multinode-integration-ubuntu-bionic
        - openstack-infra-multinode-integration-ubuntu-trusty
        - openstack-infra-multinode-integration-ubuntu-xenial
        - openstack-infra-multinode-integration-opensuse423
        - zuul-jobs-tox-linters
        - zuul-jobs-test-install-nodejs
        - zuul-jobs-test-install-pdk-dependencies
        - zuul-jobs-test-upload-git-mirror
        - zuul-jobs-test-registry
        - tox-py27
        - tox-py35
    post:
      jobs:
        - publish-zuul-docs
