# Note, this file is only part of the project definition; there is a project
# definition in each file in this directory as well which is combined with
# this.

- project:
    templates:
      - build-tox-docs
    check:
      jobs:
        - tox-py27
        - tox-py35
    gate:
      jobs:
        - tox-py27
        - tox-py35
    post:
      jobs:
        - publish-zuul-docs
