- name: Add project atomic PPA
  apt_repository:
    repo: ppa:projectatomic/ppa
  become: true
- name: Install packages
  package:
    name:
      - cri-o-1.15
      - containernetworking-plugins
      - podman
      - cri-tools
    state: present
  become: true
- name: Fix conmon symlink
  file:
    src: /usr/bin/conmon
    dest: /usr/libexec/crio/conmon
    owner: root
    group: root
    state: link
  become: true
- name: Set crio cgroup driver
  ini_file:
    path: /etc/crio/crio.conf
    section: crio.runtime
    option: cgroup_manager
    value: '"cgroupfs"'
  become: true
