- hosts: all
  tasks:
    - include_role:
        name: helm-template
      vars:
        helm_release_name: "{{ item.key }}"
        helm_chart: "{{ item.value }}"
      loop: "{{ helm_charts | dict2items }}"
