- name: Update zypper cache
  zypper:
    update_cache: yes
  become: yes

- name: Set node package name
  set_fact:
    nodejs_pkg: "nodejs{{ node_version }}"

- name: Install NodeJS
  package:
    name: "{{ nodejs_pkg }}"
    state: latest
  become: yes
  tags:
    # Ignore ANSIBLE0010: We really want latest version
    - skip_ansible_lint
