# This is used by the delete tasks
- name: Get dockerhub JWT token
  no_log: true
  uri:
    url: "https://hub.docker.com/v2/users/login/"
    body_format: json
    body:
      username: "{{ docker_credentials.username }}"
      password: "{{ docker_credentials.password }}"
  register: jwt_token
- name: Promote image
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image
  include_tasks: promote-retag.yaml
- name: Delete obsolete tags
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image
  include_tasks: promote-cleanup.yaml
