- name: Push tag to intermediate registry
  command: >-
    skopeo --insecure-policy copy
    --src-creds={{ buildset_registry.username }}:{{ buildset_registry.password }}
    --dest-creds={{ intermediate_registry.username }}:{{ intermediate_registry.password }}
    docker://{{ buildset_registry.host }}:{{ buildset_registry.port }}/{{ image.repository }}:{{ image_tag }}
    docker://{{ intermediate_registry.host }}:{{ intermediate_registry.port}}/{{ image.repository }}:{{ zuul.build }}_{{ image_tag}}
  loop: "{{ image.tags | default(['latest']) }}"
  loop_control:
    loop_var: image_tag
  # no_log: true  TODO(corvus) replace

- name: Return artifact to Zuul
  zuul_return:
    data:
      zuul:
        artifacts:
          "image_{{ image.repository }}:{{ image_tag }}":
            url: "docker://{{ intermediate_registry.host }}:{{ intermediate_registry.port}}/{{ image.repository }}:{{ zuul.build }}_{{ image_tag}}"
            metadata:
              type: container_image
              repository: "{{ image.repository }}"
              tag: "{{ image_tag }}"
  loop: "{{ image.tags | default(['latest']) }}"
  loop_control:
    loop_var: image_tag
