- hosts: all
  roles:
    - install-podman

- hosts: all
  tasks:

    - name: Exercise podman
      command: /usr/bin/podman info
      register: output

    - name: Debug output
      debug:
        msg: '{{ output.stdout }}'
