- name: Install projectatomic PPA
  apt_repository:
    repo: 'ppa:projectatomic/ppa'
    state: present
  become: yes

- name: Install podman
  package:
    name:
      - podman
      - uidmap
    state: present
  become: yes
