- name: Set up docker mirrors
  include_role:
    name: use-docker-mirror

- name: Install docker-ce from upstream
  include: upstream.yaml
  when: use_upstream_docker

- name: Install docker from distro
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.{{ ansible_architecture }}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - "default.yaml"
      paths:
        - distros
  when: not use_upstream_docker

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups:
      - "{{ docker_group }}"
    append: yes

- name: Assure docker service is running
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: Correct group ownership on docker sock
  become: yes
  file:
    path: /var/run/docker.sock
    group: "{{ docker_group }}"

- name: Reset ssh connection to pick up docker group
  meta: reset_connection

- name: Validate ability to talk with docker
  command: docker ps
  args:
    warn: no
