- name: Install pre-reqs
  package:
    name: "{{ _docker_upstream_distro_required_packages }}"
    state: present
  become: yes

- name: Add docker GPG key
  become: yes
  apt_key:
    data: "{{ docker_gpg_key }}"

# TODO(mordred) We should add a proxy cache mirror for this
- name: Add docker apt repo
  become: yes
  template:
    dest: /etc/apt/sources.list.d/docker.list
    group: root
    mode: 0644
    owner: root
    src: sources.list.j2

- name: Install docker
  become: yes
  apt:
    name: "{{ docker_upstream_distro_packages }}"
    state: present
    update_cache: yes
  notify: Restart docker
