---

- name: Install pre-reqs
  package:
    name: "{{ _docker_upstream_distro_required_packages }}"
    state: present
  become: yes

- name: Create tmp gpg key file
  copy:
    content: "{{ docker_gpg_key }}"
    dest: /tmp/key.gpg

- name: Import gpg key
  rpm_key:
    state: present
    key: /tmp/key.gpg

# TODO(mordred) We should add a proxy cache mirror for this
- name: Add docker repo
  become: yes
  copy:
    dest: /etc/yum.repos.d/docker-ce.repo
    group: root
    mode: 0644
    owner: root
    src: "{{ docker_repo_template }}"

- name: Install docker
  become: yes
  package:
    name: "{{ docker_upstream_distro_packages }}"
    state: present
  notify: Restart docker
